---
# docker-compose up -d
services:
  wavelog-db:
    image: docker.io/mariadb:11.3
    container_name: wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog # <- Insert a strong password here
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

  wavelog-main:
    container_name: wavelog-main
    image: ghcr.io/wavelog/wavelog:latest
    depends_on:
      - wavelog-db
    environment:
      CI_ENV: docker
    volumes:
      - wavelog-config:/var/www/html/application/config/docker
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-userdata:/var/www/html/userdata
    ports:
      - "8086:80"
    restart: unless-stopped
    deploy:
      labels:
        caddy: localhost
        caddy.reverse_proxy: "{{upstreams 8086}}"
        caddy.tls: "internal"


  watchtower:
    image: docker.io/containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The Caddy server container.
  caddy:
    # https://hub.docker.com/_/caddy
    image: docker.io/caddy:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    # Map the app container exposed port to the host port.
    ports:
      - 443:443
      - 2019:2019
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    # Caddy config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    # Caddy certificate authority (CA)
      - $PWD/certificate-authority:/data/caddy/pki/authorities/local

# sudo cp certificate-authority/intermediate.crt /usr/local/share/ca-certificates/
# sudo update-ca-certificates    

volumes:
  wavelog-dbdata:
  wavelog-uploads:
  wavelog-userdata:
  wavelog-config:
  caddy-data:
  caddy-config:
